import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Views/NavBar";
import Wraper from "@/components/Views/Wraper";
import Footer from "@/components/Views/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wraper>
          <NavBar />
          {children}
        </Wraper>
        <Footer />
      </body>
    </html>
  );
}
